- name: Install httpd (yum)
  yum:
    name: "{{ _packages + httpd_packages }}"
    state: present

- name: Enable httpd
  systemd:
    name: "{{ httpd_service_name }}"
    enabled: yes

- name: Listen on default ports
  lineinfile:
    path: "{{ httpd_ports_config }}"
    line: "Listen {{ item }}"
    regexp: "^Listen {{ item }}$"
  loop: [ "{{ _http_port }}", "{{ _https_port }}" ]
  notify: restart httpd

- name: Listen on all http ports
  lineinfile:
    path: "{{ httpd_ports_config }}"
    line: "Listen {{ item.http_port }}"
    regexp: "^Listen {{ item.http_port }}$"
  loop: "{{ httpd_vhosts }}"
  when:
    - "item.http_port is defined" 
  notify: restart httpd

- name: Listen on all https ports
  lineinfile:
    path: "{{ httpd_ports_config }}"
    line: "Listen {{ item.https_port }}"
    regexp: "^Listen {{ item.https_port }}$"
  loop: "{{ httpd_vhosts }}"
  when:
    - "item.https_port is defined"
  notify: restart httpd